title: latex-template
baseurl: "/latex-template"
url: "https://kaf105-mai.github.io" 

remote_theme: just-the-docs/just-the-docs
# theme: just-the-docs

permalink: pretty
exclude: 
  - "Template.pdf"

search_enabled: false

plugins:
  - jekyll-seo-tag

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
  # ignore:
  #   envs: all
